### ISSUE TITLE
dataset_generation_training issue

### ISSUE THREAD

**Issue by aarontan-git** [romarcg/traversability_estimation_pioneer#2]
Hello,

I am attempting to run the dataset_generation_training.py file however i am running in to the below issue.

The error message reads:

```
Traceback (most recent call last):
  File "dataset_generation_training.py", line 594, in <module>
    callbacks=[custom_callbacks,keras.callbacks.TensorBoard(log_dir='./logs/'+time.strftime("%Y%m%d%H%M%S"), histogram_freq=0, write_graph=False, write_images=False)]
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/keras/legacy/interfaces.py", line 91, in wrapper
    return func(*args, **kwargs)
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/keras/engine/training.py", line 1418, in fit_generator
    initial_epoch=initial_epoch)
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/keras/engine/training_generator.py", line 251, in fit_generator
    callbacks.on_epoch_end(epoch, epoch_logs)
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/keras/callbacks.py", line 79, in on_epoch_end
    callback.on_epoch_end(epoch, logs)
  File "dataset_generation_training.py", line 376, in on_epoch_end
    auc_epoch = sklearn.metrics.roc_auc_score(self.validation_data[1][0], y_pred)
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/sklearn/metrics/ranking.py", line 355, in roc_auc_score
    sample_weight=sample_weight)
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/sklearn/metrics/base.py", line 76, in _average_binary_score
    return binary_metric(y_true, y_score, sample_weight=sample_weight)
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/sklearn/metrics/ranking.py", line 327, in _binary_roc_auc_score
    sample_weight=sample_weight)
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/sklearn/metrics/ranking.py", line 622, in roc_curve
    y_true, y_score, pos_label=pos_label, sample_weight=sample_weight)
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/sklearn/metrics/ranking.py", line 398, in _binary_clf_curve
    check_consistent_length(y_true, y_score, sample_weight)
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/sklearn/utils/validation.py", line 205, in check_consistent_length
    " samples: %r" % [int(l) for l in lengths])
ValueError: Found input variables with inconsistent numbers of samples: [2, 10000]

```

The above error message seems to happen after one epoch. The following is a part of the error message that precede the above:

```
name: Quadro K2200 major: 5 minor: 0 memoryClockRate(GHz): 1.124
pciBusID: 0000:01:00.0
totalMemory: 3.94GiB freeMemory: 3.13GiB
2019-06-24 13:19:15.345383: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1511] Adding visible gpu devices: 0
2019-06-24 13:19:25.558085: I tensorflow/core/common_runtime/gpu/gpu_device.cc:982] Device interconnect StreamExecutor with strength 1 edge matrix:
2019-06-24 13:19:25.558164: I tensorflow/core/common_runtime/gpu/gpu_device.cc:988]      0 
2019-06-24 13:19:25.558208: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1001] 0:   N 
2019-06-24 13:19:25.558586: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 2841 MB memory) -> physical GPU (device: 0, name: Quadro K2200, pci bus id: 0000:01:00.0, compute capability: 5.0)
Epoch 1/50
100/100 [==============================] - 122s 1s/step - loss: 0.5160 - acc: 0.7639 - val_loss: 0.4441 - val_acc: 0.8033
```

Please let me know if you've seen something like this before?

Thank you,
Aaron

**Comment by romarcg** [comment]
On Tue, 25 Jun, 2019 at 10:48 PM, a <notifications@github.com> wrote:
> sklearn.metrics.roc_auc_score(self.validation_data[1][0], y_pred)

I did not remember something like this.

However, the error at the end of the traceback

ValueError: Found input variables with inconsistent numbers of samples: 
[2, 10000]

indicates that y_pred is of that size while the validation input (I 
assume) is only [1,10000]. Can you paste the size of the validation 
vector?

**Comment by aarontan-git** [comment]
Hello,

Thanks for your reply.

I agree there is a problem with the following line.

```
sklearn.metrics.roc_auc_score(self.validation_data[1][0], y_pred)
```

Below are some array/list sizes that I gathered.

```
x_te row: 10000
x_te column: 60
y_te row: 10000
y_te column: 2
validation_data row: 3
validation_data column: 10000
y_pred row: 10000
y_pred column: 2
```

After commenting out the *sklearn.metrics.roc_auc_score(self.validation_data[1][0], y_pred)* line, training was able to finish (generated the model file). However, upon finishing, the current error message that I see is as shown below.

```
Traceback (most recent call last):
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/joblib/externals/loky/process_executor.py", line 418, in _process_worker
    r = call_item()
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/joblib/externals/loky/process_executor.py", line 272, in __call__
    return self.fn(*self.args, **self.kwargs)
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/joblib/_parallel_backends.py", line 567, in __call__
    return self.func(*args, **kwargs)
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/joblib/parallel.py", line 225, in __call__
    for func, args, kwargs in self.items]
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/joblib/parallel.py", line 225, in <listcomp>
    for func, args, kwargs in self.items]
  File "dataset_generation_training.py", line 396, in mc_extract_features_cnn
    patch = skimage.transform.warp(multiprocessing_hm, trf,output_shape=(edges,edges),mode="edge")
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/skimage/transform/_warps.py", line 865, in warp
    order=order, mode=mode, cval=cval)
  File "skimage/transform/_warps_cy.pyx", line 122, in skimage.transform._warps_cy._warp_fast
  File "stringsource", line 654, in View.MemoryView.memoryview_cwrapper
  File "stringsource", line 349, in View.MemoryView.memoryview.__cinit__
ValueError: buffer source array is read-only
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dataset_generation_training.py", line 641, in <module>
    test_fitted_model_full_map_stride_cnn(model,heightmap_png,patch_size, patch_resize, 0, stride)
  File "dataset_generation_training.py", line 434, in test_fitted_model_full_map_stride_cnn
    X_mp = Parallel(n_jobs=4)(delayed(mc_extract_features_cnn)(d["hm_x"],d["hm_y"],np.rad2deg(d["G"]),edges,resize,scale=1) for idx,d in full_data.iterrows())
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/joblib/parallel.py", line 934, in __call__
    self.retrieve()
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/joblib/parallel.py", line 833, in retrieve
    self._output.extend(job.get(timeout=self.timeout))
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/joblib/_parallel_backends.py", line 521, in wrap_future_result
    return future.result(timeout=timeout)
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 405, in result
    return self.__get_result()
  File "/usr/lib/python3.5/concurrent/futures/_base.py", line 357, in __get_result
    raise self._exception
ValueError: buffer source array is read-only

```
# Question

1. Do you know how to fix the inconsistent number of samples issue caused by the mentioned line?

2. Have you seen the second error message that happens after finishing training? 

## Edit
It turns out that the error message in question 2 is the result of not having the correct version of joblib.

**Comment by aarontan94** [comment]
> On Tue, 25 Jun, 2019 at 10:48 PM, a ***@***.***> wrote: sklearn.metrics.roc_auc_score(self.validation_data[1][0], y_pred)
> I did not remember something like this. However, the error at the end of the traceback ValueError: Found input variables with inconsistent numbers of samples: [2, 10000] indicates that y_pred is of that size while the validation input (I assume) is only [1,10000]. Can you paste the size of the validation vector?

How do I find the size of the valdiation vector?

**Comment by romarcg** [comment]
Hi,

I will try to replicate the error in question 1 to see where the issue may be. So far, I see it comes from the inconsistent size from y_pred and validation. From your last message I see that `validation_data row: 3`, while `y_pred` is 2.

Good that you found out the answer for question 2. I was not aware of such version issues. 

Omar
