### ISSUE TITLE
evaluation.py issue

### ISSUE THREAD

**Issue by aarontan-git** [romarcg/traversability_estimation_pioneer#3]
Hello,

I am attempting to run the evaluation.py file. Currently I am running in to the below error message.

```
Traceback (most recent call last):
  File "evaluation.py", line 482, in <module>
    temp_thm = test_fitted_model_full_map_stride_cnn(model,heightmap_png, patch_size, patch_resize, 0, stride)
  File "evaluation.py", line 164, in test_fitted_model_full_map_stride_cnn
    y_pred = fitted.predict(X)
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/keras/engine/training.py", line 1149, in predict
    x, _, _ = self._standardize_user_data(x)
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/keras/engine/training.py", line 751, in _standardize_user_data
    exception_prefix='input')
  File "/home/usar/.virtualenvs/tran/lib/python3.5/site-packages/keras/engine/training_utils.py", line 138, in standardize_input_data
    str(data_shape))
ValueError: Error when checking input: expected conv2d_1_input to have shape (60, 60, 1) but got array with shape (40, 40, 1)
```

Please let me know if you've seen something like this before?

**Comment by aarontan-git** [comment]
Hello,

It seems the patch_size and patch_resize in line 465-466 should be set to 60 to resolve the problem mentioned above.

However, the next error message I receive when trying to run this code is now as shown below:

```
Generating traversability map/graph for 8 orientations
Extracting features (only patch cropping) from the height map: 
Estimating traversability for all the patches
Traceback (most recent call last):
  File "/home/usar/.virtualenvs/est/lib/python3.5/site-packages/networkx/classes/function.py", line 659, in set_node_attributes
    for n, v in values.items():
AttributeError: 'str' object has no attribute 'items'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "evaluation.py", line 494, in <module>
    full_data, y_pred, G = generate_traversability_graph_cnn(model, heightmap_png, patch_size, patch_resize, stride, 8)
  File "evaluation.py", line 289, in generate_traversability_graph_cnn
    nx.set_node_attributes(G,"label",g_labels)
  File "/home/usar/.virtualenvs/est/lib/python3.5/site-packages/networkx/classes/function.py", line 666, in set_node_attributes
    G.nodes[n][name] = values
TypeError: unhashable type: 'dict'
```

Could you please help me with this issue?

Thanks

**Comment by romarcg** [comment]
Hi,

It's good to hear that you managed to fix the issue. I will update 
those points in a future commit.

For the latest error, it may be related to the networkx library. Try 
modifying line 289 in evaluation.py to:

nx.set_node_attributes(G, name="label", values=g_labels)
